admin:
  existingSecret: grafana-secrets
service:
  type: ClusterIP
downloadDashboardsImage:
  repository: dciangot/curl
  tag: latest
  #repository: curlimages/curl 
  #tag: 7.73.0
  sha: ""
  pullPolicy: IfNotPresent
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc
      access: proxy
      isDefault: true
dashboards:
  default:
    prometheus-stats:
      # Ref: https://grafana.com/dashboards/10000
      gnetId: 10000
      revision: 1
      datasource: Prometheus
    kube-eagle-stats:
      # Ref: https://grafana.com/dashboards/9871
      gnetId: 9871
      revision: 2
      datasource: Prometheus
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards
grafana.ini:
  server:
    domain: "{{ nginx_ingress.dns_name }}"
    root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
    serve_from_sub_path: true
  security:
    cookie_secure: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "{{ cluster_issuer_name }}"
  path: /grafana
  hosts:
    - "{{ nginx_ingress.dns_name }}"
  tls:
    - hosts:
      - "{{ nginx_ingress.dns_name }}"
      secretName: grafana-selfsigned
